### ISSUE TITLE
Unable to publish Verification results using Spring Provider JVM plugin

### ISSUE THREAD

**Issue by mattrlong** [DiUS/pact-jvm#696] opened 2018-06-11 09:46 UTC
When validating consumer's requests using 3.5.17 of the Spring Provider JVM plugin I'm unable to publish the results back to the Pact Broker. 

The Pact is successfully pulled down from the broker at the start of the test, but when complete the debug statement 'Skipping publishing verification results for source ....' is output to console. 

When downgrading to 3.5.16 of the plugin the reports are successfully pushed.

**Comment by rholshausen** [comment] 2018-06-13 05:12
This is a duplicate of #694

**Closed** 2020-02-22 22:46 UTC
Labels: duplicate
