### ISSUE TITLE
How to publish tags to PACT Broker from Consumer JUnit Test

### ISSUE THREAD

**Issue by correctclick** [DiUS/pact-jvm#403] opened 2017-04-10 23:22 UTC
We are using JUnit for creating & publishing PACT files to PACT Broker. It's very clear on the provider test, as to how to use different tags while fetching the PACT File. However i coulnd't find how to publish PACT files with tags on JVM. Could you please advise?

**Comment by uglyog** [comment] 2017-04-14 01:37
This feature will need to be added to the pact publish task

**Comment by wldandan** [comment] 2017-04-16 03:07
I was using 3.4.2 Pact gradle plugin to publish pact file, but it always got "bad request". Not sure what the root cause is.

**Comment by uglyog** [comment] 2017-04-16 06:48
"bad request" is the response when the pact broker has rejected the pact file. This is normally due to the provider name being similar to another one in the repository. If you run the publish task with debug level logging, you should see more information.

**Comment by suresh2000** [comment] 2017-06-08 22:14
I am Using Maven version and not able to tag the pact file.  Here is my configuration
			<plugin>
				<groupId>au.com.dius</groupId>
				<artifactId>pact-jvm-provider-maven_2.11</artifactId>
				<version>3.3.8</version>
				<configuration>
					<pactBrokerUrl>http://localhost:80</pactBrokerUrl>
					<projectVersion>1.0.2</projectVersion>
					<tags>
                  		<tag>DEV</tag>
             		 </tags>

**Comment by dengayevskiy** [comment] 2017-11-07 15:33
Hi! Any updates on this?

**Comment by uglyog** [comment] 2017-11-15 01:48
The Gradle plugin can publish pacts with tags. The documentation for this needs to be updated.

The Maven plugin still needs to be updated to support tags.

**Comment by Tom-Van-Asch** [comment] 2018-01-08 13:05
Hello

When will this change be done for the maven plugin? Is it already on the roadmap for the next release?

Kind regards
Tom

**Comment by uglyog** [comment] 2018-01-15 01:30
Yes, this will be fixed for the next release (3.5.12).

**Comment by Thadir** [comment] 2018-04-20 12:45
It seems that this is already released (the current version of pact-jvm is 3.5.14)

**Comment by uglyog** [comment] 2018-04-21 02:32
The maven plugin in 3.5.14 can publish pacts with tags. The title of this issue seems to be about publishing from a JUnit test, which is not supported.

**Closed** 2020-01-18 12:28 UTC
Labels: enhancement
