### ISSUE TITLE
Class Configuration error

### ISSUE THREAD

**Issue by leonleo997** [DiUS/pact-jvm#964] opened 2019-10-23 20:30 UTC
Hello,
I'm trying to make fail my tests intencionally to look the published errors on pact broker but I got this class configuration error:
```
java.lang.ClassCastException: java.lang.AssertionError cannot be cast to java.lang.Exception

	at au.com.dius.pact.core.pactbroker.PactBrokerClient.buildPayload(PactBrokerClient.kt:243)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient.publishVerificationResults(PactBrokerClient.kt:167)
	at au.com.dius.pact.core.pactbroker.PactBrokerClient.publishVerificationResults$default(PactBrokerClient.kt:162)
	at au.com.dius.pact.provider.DefaultVerificationReporter.publishResult(VerificationReporter.kt:45)
	at au.com.dius.pact.provider.DefaultVerificationReporter.reportResults(VerificationReporter.kt:32)
	at au.com.dius.pact.provider.VerificationReporter$DefaultImpls.reportResults$default(VerificationReporter.kt:14)
	at au.com.dius.pact.provider.DefaultTestResultAccumulator.updateTestResult(TestResultAccumulator.kt:48)
	at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.kt:157)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:137)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.kt:51)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
```
These are my annotations:
```
@RunWith(RestPactRunner.class)
@Provider("clarifi-loan-handler-service")
@PactBroker(host = "localhost", port = "80")
@VerificationReports(["markdown"])
```
![image](https://user-images.githubusercontent.com/35767777/67431158-52445980-f5a9-11e9-8fe9-be08a667b876.png)

**Comment by uglyog** [comment] 2019-10-27 04:34
Duplicate of #935

**Closed by uglyog** 2019-10-27 04:34 UTC
Labels: duplicate
