### ISSUE TITLE
Provider test fails when eachLike is used in consumer

### ISSUE THREAD

**Issue by kmaddileti** [DiUS/pact-jvm#156] opened 2015-08-24 20:29 UTC
Provider: 

```
@Grab(group='io.ratpack', module='ratpack-groovy', version='0.9.19')
import static ratpack.groovy.Groovy.ratpack

ratpack {
	handlers {
		get {
			response.headers.set 'Content-Type', 'application/json;charset=UTF-8'
			response.send """[ { "id": "1", "name": "name-1" },{ "id": "2", "name": "name-2" },{ "id": "3", "name": "name-3" },{ "id": "4", "name": "name-4" },{ "id": "5", "name": "name-5" } ]"""

		}

	}
}
```

Consumer : "au.com.dius:pact-jvm-consumer-groovy-v3_2.11:3.0.1"
Producer Tests: 'au.com.dius:pact-jvm-provider-gradle_2.11:2.2.12'

```
class EachLikeTest {

    @Test
    void "Verify eachLike when Array is returned"() {
        def nameService = new PactBuilder()
        nameService {
            serviceConsumer "NameConsumer"
            hasPactWith "NameService"
            port 1234

            uponReceiving('A GET request to retrieve names')
            withAttributes(method: 'get', path: '/',
                    headers: ['Content-Type': 'application/json; charset=UTF-8'])
            willRespondWith(status: 200, headers: ['Content-Type': 'application/json;charset=UTF-8'])
             withBody eachLike {
                       id regexp(~/\w+/)
                       name regexp(~/\w+/)
            }
        }

        VerificationResult result = nameService.run {
            def client = new RESTClient('http://localhost:1234/')
            def nameResponse = client.get(path: '/') {
                type 'application/json'
            }
            assert nameResponse.statusCode == 200
            assert nameResponse.contentType == 'application/json'
        }
    }
}
```

Provider Gradle Build File: 

```
pact {
    serviceProviders {
        NameService {
            protocol = 'http'
            host = 'localhost'
            port = 5050
            path = '/'

            hasPactWith('NameConsumer') {
                pactFile = file("$projectDir/pacts/NameConsumer-NameService.json")
            }
        }
    }
}
```

Error Message
Verifying a pact between  NameConsumer and NameService
  [Using file XXXX (edited to private info)]
  A GET request to retrieve names       
    returns a response which            
      has status code 200 (OK)          
      includes headers                  
        "Content-Type" with value "application/json;charset=UTF-8" (OK)
      has a matching body (FAILED)      
                                        
Failures:

0) Verifying a pact between NameConsumer and NameService - A GET request to retrieve names returns a response which has a matching body
      $.body -> Expected List(Map(id -> 1, name -> name-1), Map(id -> 2, name -> name-2), Map(id -> 3, name -> name-3), Map(id -> 4, name -> name-4), Map(id -> 5, name -> name-5)) to
be the same type as List(Map(id -> ww, name -> w))
      $.body.0.name -> Expected 'name-1' to match '\w+'
      $.body.1.name -> Expected 'name-2' to match '\w+'
      $.body.2.name -> Expected 'name-3' to match '\w+'
      $.body.3.name -> Expected 'name-4' to match '\w+'
      $.body.4.name -> Expected 'name-5' to match '\w+'
                                        
      Diff:                             
                                        
      @2                                
          {                             
      -        "id": "ww",              
      -        "name": "w"              
      +        "id": "1",               
      +        "name": "name-1"         
      +    },                           
      +    {                            
      +        "id": "2",               
      +        "name": "name-2"         
      +    },                           
      +    {                            
      +        "id": "3",               
      +        "name": "name-3"         
      +    },                           
      +    {                            
      +        "id": "4",               
      +        "name": "name-4"         
      +    },                           
      +    {                            
      +        "id": "5",               
      +        "name": "name-5"         
          }                             
                                        
                                        
:pactVerify_NameService FAILED

**Comment by kmaddileti** [comment] 2015-08-25 14:17
Forgot to add the generated pact file.

```
{
  "provider" : {
    "name" : "NameService"
  },
  "consumer" : {
    "name" : "NameConsumer"
  },
  "interactions" : [ {
    "description" : "A GET request to retrieve names",
    "request" : {
      "method" : "GET",
      "path" : "/",
      "headers" : {
        "Content-Type" : "application/json; charset=UTF-8"
      }
    },
    "response" : {
      "status" : 200,
      "headers" : {
        "Content-Type" : "application/json;charset=UTF-8"
      },
      "body" : [ {
        "id" : "ww",
        "name" : "w"
      } ],
      "matchingRules" : {
        "$.body" : {
          "match" : "type"
        },
        "$.body[*].id" : {
          "regex" : "\\w+"
        },
        "$.body[*].name" : {
          "regex" : "\\w+"
        }
      }
    }
  } ],
  "metadata" : {
    "pact-specification" : {
      "version" : "2.0.0"
    },
    "pact-jvm" : {
      "version" : "3.0.1"
    }
  }
}
```

**Comment by uglyog** [comment] 2015-08-29 03:38
I think the issue is with the regular expression `~/\w+/` which matches whole words only (a-z). The hyphen and number in the names is causing the problem. `~/[a-zA-Z0-9\-]+/` will match it.

If your names are always in the from <name>-<number>, you can also use `/\w+\-\d+/`.

**Comment by kmaddileti** [comment] 2015-09-02 21:47
I have updated the v to 3.0.2 and rewrote the expression as follows: 

```
withBody eachLike {
                     id regexp(~/[0-9]/)
                     name regexp(~/[a-z]+\-[0-9]/)
             }
```

I'm still getting the same error message: 

Failures:

0) Verifying a pact between NameConsumer and NameService - A GET request to retrieve names returns a response which has a matching body
      $.body -> Expected List(Map(id -> 1, name -> name-1), Map(id -> 2, name -> name-2), Map(id -> 3, name -> name-3), Map(id -> 4, name -> name-4), Map(id -> 5, name -> name-5)) to be
the same type as List(Map(id -> 8, name -> m-5))

      Diff:

      @2
          {
      -        "id": "8",
      -        "name": "m-5"
      +        "id": "1",
      +        "name": "name-1"
      +    },
      +    {
      +        "id": "2",
      +        "name": "name-2"
      +    },
      +    {
      +        "id": "3",
      +        "name": "name-3"
      +    },
      +    {
      +        "id": "4",
      +        "name": "name-4"
      +    },
      +    {
      +        "id": "5",
      +        "name": "name-5"
          }

Note: I have tried many other variations like /\w+\-\d+/ and they all fail with exactly the same message.

Why is the expected list only of length 1, when the actual list of maps is of length 5? Could this have something to do with the failure?

$.body -> Expected List(Map(id -> 1, name -> name-1), Map(id -> 2, name -> name-2), Map(id -> 3, name -> name-3), Map(id -> 4, name -> name-4), Map(id -> 5, name -> name-5)) to be
the same type as List(Map(id -> 8, name -> m-5))

**Comment by uglyog** [comment] 2015-09-04 09:06
There is something wrong with the eachLike matcher. I'll have a look into
it.

**Comment by uglyog** [comment] 2015-09-11 04:59
I've pushed a fix for this regression. It should now pass because the eachLike matcher will cause the lists to be compared by their type.

**Comment by kmaddileti** [comment] 2015-09-16 18:58
When is it expected to be published to plugin repository, I'm defaulting to here and 3.0.1 is listed as the latest here.
https://plugins.gradle.org/plugin/au.com.dius.pact

**Comment by kmaddileti** [comment] 2015-09-16 19:58
Looks like plugins { } defaults to org.gradle namespace, switching to 
apply plugin: "au.com.dius.pact" seems to be working. Will update after I'm able to get eachLike to work.

**Comment by kmaddileti** [comment] 2015-09-16 20:21
Unfortunately, I'm getting the exact same error message. 


One question, does it matter if the pact file was published with 3.0.2. I didn't see anywhere that it cares about the meta data.

 "metadata": {
    "pact-specification": {
      "version": "2.0.0"
    },
    "pact-jvm": {
      "version": "3.0.2" <<<
    }

**Comment by kmaddileti** [comment] 2015-09-16 20:49
I have verified that the build script is picking up the latest version

task showClasspath << {
    buildscript.configurations.classpath.each { if(it.name.toLowerCase().contains("pact")) println it.name }
}

gradlew showClasspath
:showClasspath
pact-jvm-provider-gradle_2.11-3.0.3.jar
pact-jvm-provider_2.11-3.0.3.jar
pact-jvm-matchers_2.11-3.0.3.jar
pact-jvm-model_2.11-3.0.3.jar
pact-jvm-model-v3_2.11-3.0.3.jar

BUILD SUCCESSFUL

Total time: 3.76 secs

No luck with the fix.

**Comment by uglyog** [comment] 2015-09-16 23:10
This fix will be in version 3.0.4, which I will release shortly.

**Comment by uglyog** [comment] 2015-09-18 02:46
Version 3.0.4 has been released

**Comment by kmaddileti** [comment] 2015-09-18 13:31
Great, I was able to test it out and it works. Thanks again for looking into it and providing a fix.

**Closed** 2015-09-20 23:11 UTC
Labels: bug, question
