### ISSUE TITLE
Verification results are not pushed back to Pact Broker

### ISSUE THREAD

**Issue by dervism** [DiUS/pact-jvm#694] opened 2018-06-10 08:22 UTC
I have a Maven-based provider test-app that I am using to compare Maven and Gradle, both using version 3.5.17.

Source: https://github.com/dervism/person-provider

The verification results are not pushed back to my Pact Broker (https://norwegianlga.pact.dius.com.au/). I have tested with JDK10 and also downgraded to JDK8, but still my provider test are running fine and no update are happening to my Pact Broker.

Reverting back to 3.5.16 and JUnit4 (see branch 'junit4' in my repo) solved the issue. Also, one of my Gradle-based examples that uses the Gradle Pact plugin (also 3.5.17) are working and correctly publishes the verification results.

Do you have any idea what is going on in my Maven-app?

**Comment by uglyog** [comment] 2018-06-11 02:58
A fix for issue #667 has caused this regression. I'm either going to revert that change, or see if I can fix both.

**Comment by uglyog** [comment] 2018-06-11 04:03
Actually, the issue is with the JUnit 5 implementation. It doesn't verify the result of all the tests, so the publish verification results is never called.

**Comment by uglyog** [comment] 2018-06-17 07:34
Fix has been released with version 3.5.18

**Closed by uglyog** 2018-06-17 07:34 UTC
Labels: bug
