### ISSUE TITLE
JUnit Consumer throws 'Text must not be null' error message

### ISSUE THREAD

**Issue by bbarke** [DiUS/pact-jvm#216] opened 2016-02-18 00:57 UTC
JUnit Consumer throws 'Text must not be null' error message. I've tried several things to get it to work properly - set the bodies to empty strings, a single string, etc..

Here is a link to the code:
https://gist.github.com/bbarke/fe187c0b4bf91a51f615
Here is a link to the stacktrace:
https://gist.github.com/bbarke/c6a431af368691e38fc7

**Comment by uglyog** [comment] 2016-02-18 04:34
I've confirmed the defect. It is the GET request that is causing the failure, looks like the body is null when it is being compared.

**Comment by uglyog** [comment] 2016-02-18 06:23
This issue should be fixed now. It was a case where the body of the GET request was an empty string, so the JSON parser was failing.

**Comment by bbarke** [comment] 2016-02-18 17:07
Thank you for the quick fix! I've built the source locally and confirm it is working. I'll continue to develop my tests with this revision and let you know if I seen any other issues.

**Closed** 2016-03-12 03:11 UTC
Labels: bug
