### ISSUE TITLE
Data Generator fails when inside an object

### ISSUE THREAD

**Issue by a-ster** [DiUS/pact-jvm#708] opened 2018-06-19 01:13 UTC
After upgrading from 3.5.10 to 3.5.18, pact generation and verification failed due to:
1. Pact generation: Tests where the value is generated by pact started failing.
2. Pact verification: Applied the work-around for Issue 1 to generate pact. But pact verification failed because the matchers were not prefixed with "$".

**Issue 1:**
This is how the pact looks like:
```
PactDslJsonBody responseBody = new PactDslJsonBody();
    responseBody.object("_warnings");
    responseBody.integerType("code", 404);
    responseBody.stringType("message");
    responseBody.closeObject();

RequestResponsePact pact = ConsumerPactBuilder
        .consumer("self")
        .hasPactWith("api")
        .uponReceiving("Not found - Return 404")
        .path("/v1/my/api/get")
        .method("GET")
        .willRespondWith()
        .status(404)
        .body(responseBody)
        .toPact();
```
When running this against 3.5.10, the test passed.
![image](https://user-images.githubusercontent.com/28387803/41570216-f027864c-73c1-11e8-9fd8-ec06aa095ab3.png)

After upgrading to 3.5.18, the test failed.
![image](https://user-images.githubusercontent.com/28387803/41570289-40a16930-73c2-11e8-89fd-8b2f4644440f.png)

The work-around is to provide an example value instead of letting pact generate the data.
```
    PactDslJsonBody responseBody = new PactDslJsonBody();
    responseBody.object("_warnings");
    responseBody.integerType("code", 404);
    responseBody.stringType("message", "test message");
    responseBody.closeObject();
```
**Issue 2:**
Though the work-around allows the pact to be generated, the verification failed because the matching rules do not have "$" prefixed to the attribute.

Console log
![image](https://user-images.githubusercontent.com/28387803/41629957-8701d8d8-7480-11e8-9dda-53e591199448.png)

Generated Pact
![image](https://user-images.githubusercontent.com/28387803/41629979-9b5646f2-7480-11e8-9a88-b5d193ab0bb7.png)

I have to use .close() instead of .closeObject() for the pact to be generated properly.

**Comment by rholshausen** [comment] 2018-06-20 01:34
Thanks for the information. I now finally understand the cause of issue #628.

**Comment by uglyog** [comment] 2018-07-01 06:01
Should be fixed now.

**Comment by uglyog** [comment] 2018-07-01 09:41
3.5.19 has been released with this fix

**Closed by uglyog** 2018-07-01 09:41 UTC
Labels: bug
