### ISSUE TITLE
Maven Enforcer plugin error for pact consumer 3.5.16

### ISSUE THREAD

**Issue by davidkgp** [DiUS/pact-jvm#687] opened 2018-05-24 11:12 UTC
My organization enforces the maven enforcer plugin for detecting dependency convergence in our projects.Since we have decided to adapt pact consumer and pact provider testing,we are running to problems with the dependency convergence issue

Dependency convergence error for org.slf4j:slf4j-api:1.7.25 paths to dependency are:
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-org.slf4j:slf4j-api:1.7.25
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-io.github.microutils:kotlin-logging:1.4.4
      +-org.slf4j:slf4j-api:1.7.21
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-com.typesafe.scala-logging:scala-logging_2.12:3.7.2
      +-org.slf4j:slf4j-api:1.7.25
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-org.slf4j:slf4j-api:1.7.25
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-org.slf4j:slf4j-api:1.7.25
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-au.com.dius:pact-jvm-pact-broker:3.5.16
          +-org.slf4j:slf4j-api:1.7.25
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-matchers_2.12:3.5.16
        +-org.slf4j:slf4j-api:1.7.25

[WARNING] 
Dependency convergence error for org.jetbrains.kotlin:kotlin-stdlib:1.2.40 paths to dependency are:
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-org.jetbrains.kotlin:kotlin-stdlib-jre8:1.2.40
      +-org.jetbrains.kotlin:kotlin-stdlib:1.2.40
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-org.jetbrains.kotlin:kotlin-stdlib-jre8:1.2.40
      +-org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.40
        +-org.jetbrains.kotlin:kotlin-stdlib:1.2.40
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-org.jetbrains.kotlin:kotlin-reflect:1.2.40
      +-org.jetbrains.kotlin:kotlin-stdlib:1.2.40
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-io.github.microutils:kotlin-logging:1.4.4
      +-org.jetbrains.kotlin:kotlin-stdlib:1.1.1
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-au.com.dius:pact-jvm-pact-broker:3.5.16
          +-com.github.salomonbrys.kotson:kotson:2.5.0
            +-org.jetbrains.kotlin:kotlin-stdlib:1.0.6

[WARNING] 
Dependency convergence error for commons-logging:commons-logging:1.1.3 paths to dependency are:
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-com.amazonaws:aws-java-sdk-s3:1.11.30
          +-com.amazonaws:aws-java-sdk-core:1.11.30
            +-commons-logging:commons-logging:1.1.3
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-org.apache.httpcomponents:fluent-hc:4.5.5
        +-commons-logging:commons-logging:1.2

[WARNING] 
Dependency convergence error for org.scala-lang:scala-library:2.12.5 paths to dependency are:
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-org.scala-lang:scala-library:2.12.5
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-com.typesafe.scala-logging:scala-logging_2.12:3.7.2
      +-org.scala-lang:scala-library:2.12.2
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-com.typesafe.scala-logging:scala-logging_2.12:3.7.2
      +-org.scala-lang:scala-reflect:2.12.2
        +-org.scala-lang:scala-library:2.12.2
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-org.scala-lang:scala-library:2.12.5
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-matchers_2.12:3.5.16
        +-org.scala-lang:scala-library:2.12.5
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-matchers_2.12:3.5.16
        +-io.gatling:jsonpath_2.12:0.6.9
          +-org.scala-lang:scala-library:2.12.1
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-matchers_2.12:3.5.16
        +-io.gatling:jsonpath_2.12:0.6.9
          +-org.scala-lang.modules:scala-parser-combinators_2.12:1.0.5
            +-org.scala-lang:scala-library:2.12.1
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-matchers_2.12:3.5.16
        +-org.scala-lang.modules:scala-xml_2.12:1.0.6
          +-org.scala-lang:scala-library:2.12.0
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-ws.unfiltered:unfiltered-netty-server_2.12:0.9.1
        +-org.scala-lang:scala-library:2.12.1
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-ws.unfiltered:unfiltered-netty-server_2.12:0.9.1
        +-ws.unfiltered:unfiltered-netty_2.12:0.9.1
          +-org.scala-lang:scala-library:2.12.1
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-ws.unfiltered:unfiltered-netty-server_2.12:0.9.1
        +-ws.unfiltered:unfiltered-netty_2.12:0.9.1
          +-ws.unfiltered:unfiltered_2.12:0.9.1
            +-org.scala-lang:scala-library:2.12.1
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-ws.unfiltered:unfiltered-netty-server_2.12:0.9.1
        +-ws.unfiltered:unfiltered-util_2.12:0.9.1
          +-org.scala-lang:scala-library:2.12.1
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0
        +-org.scala-lang:scala-library:2.12.0

[WARNING] 
Dependency convergence error for org.dmfs:iterators:1.5 paths to dependency are:
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-au.com.dius:pact-jvm-pact-broker:3.5.16
          +-org.dmfs:rfc3986-uri:0.8
            +-org.dmfs:iterators:1.5
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-au.com.dius:pact-jvm-pact-broker:3.5.16
          +-org.dmfs:rfc3986-uri:0.8
            +-org.dmfs:optional:0.3
              +-org.dmfs:iterators:1.4

[WARNING] 
Dependency convergence error for org.apache.httpcomponents:httpclient:4.5.5 paths to dependency are:
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-au.com.dius:pact-jvm-pact-broker:3.5.16
          +-org.apache.httpcomponents:httpclient:4.5.5
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-com.amazonaws:aws-java-sdk-s3:1.11.30
          +-com.amazonaws:aws-java-sdk-core:1.11.30
            +-org.apache.httpcomponents:httpclient:4.5.2
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-org.apache.httpcomponents:httpclient:4.5.5
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-org.apache.httpcomponents:httpmime:4.5.5
        +-org.apache.httpcomponents:httpclient:4.5.5
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-org.apache.httpcomponents:fluent-hc:4.5.5
        +-org.apache.httpcomponents:httpclient:4.5.5

[WARNING] 
Dependency convergence error for com.fasterxml.jackson.core:jackson-databind:2.6.6 paths to dependency are:
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-com.amazonaws:aws-java-sdk-s3:1.11.30
          +-com.amazonaws:aws-java-sdk-core:1.11.30
            +-com.fasterxml.jackson.core:jackson-databind:2.6.6
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-au.com.dius:pact-jvm-model:3.5.16
        +-com.amazonaws:aws-java-sdk-s3:1.11.30
          +-com.amazonaws:jmespath-java:1.0
            +-com.fasterxml.jackson.core:jackson-databind:2.6.6
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-au.com.dius:pact-jvm-consumer-junit_2.12:3.5.16
    +-au.com.dius:pact-jvm-consumer_2.12:3.5.16
      +-com.fasterxml.jackson.core:jackson-databind:2.8.1
and
+-my.test.consumer:NativeConsumer:0.0.1-SNAPSHOT
  +-com.fasterxml.jackson.core:jackson-databind:2.2.3

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.402 s
[INFO] Finished at: 
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (enforce) on project ConsumerProg: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]

**Comment by rholshausen** [comment] 2018-05-28 02:53
There is not much I can directly do here. Pact-JVM is built with Gradle, you are having issues with Maven transitive dependency versions that are outside my control. You will have to pin the versions of the dependencies and add exclusions in your POM to appease the enforcer plugin.

This is a duplicate of #182

**Comment by habbo656** [comment] 2018-08-17 06:46
I also run into this issues. When you would analyze the enforcer output, you can see that there are different versions of the same library, all used by pact dependencies. It's not a matter if you use gradle or maven. Its about managing your dependencies. as an example the last one of the list:

jackson-databind
  --> version 2.8.1 comes from pact-jvm-consumer_2.12
  --> version 2.6.6 used by pact-jvm-model

All pact-x packages should use the same dependencies. Look at how Spring managage it's dependencies. They have a pom where all Versions are declared and used through all projects.

Also I run through hell as I tried to include pact into my angular app....

**Closed** 2020-02-22 22:47 UTC
Labels: duplicate
