### ISSUE TITLE
Issue for  @Pact, @PactVerification and @PactVerifyProvider. Missing $ symbol in pact.json

### ISSUE THREAD

**Issue by PDziamentsyeu** [DiUS/pact-jvm#628] opened 2018-01-23 12:08 UTC
Hello. I'm using  in my gradle this dependencies ( early i used 3.5.11)

'au.com.dius.pact' version '3.5.12'
au.com.dius:pact-jvm-provider-gradle_2.12:3.5.12
au.com.dius:pact-jvm-consumer-junit_2.12:3.5.12

after migrating to 3.5.12  i got issue for consumer.json
 ".metadata.date": {  instead "$.metadata.date": { (missing $)

As a result for pactVerify i got  a lot of warnings:

```
Path expression .payload.name is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.payload.name
^
Path expression .payload.iri is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.payload.iri
^
Path expression .metadata.messageId is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.metadata.messageId
^
Path expression .metadata.date is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.metadata.date
^
Path expression .metadata.contractVersion is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.metadata.contractVersion
^
Path expression .payload.name is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.payload.name
^
Path expression .payload.iri is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.payload.iri
^
Path expression .metadata.messageId is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.metadata.messageId
^
Path expression .metadata.date is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.metadata.date
^
Path expression .metadata.contractVersion is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.metadata.contractVersion
^
Path expression .payload.name is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.payload.name
^
Path expression .payload.iri is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.payload.iri
^
Path expression .metadata.messageId is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.metadata.messageId
^
Path expression .metadata.date is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.metadata.date
^
Path expression .metadata.contractVersion is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.metadata.contractVersion
^
Path expression .payload.name is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.payload.name
^
Path expression .payload.iri is invalid, ignoring: [1.1] failure: `$' expected but `.' found

.payload.iri
```

**Comment by uglyog** [comment] 2018-01-30 10:33
Is it possible to provide the consumer test code for this?

**Comment by PDziamentsyeu** [comment] 2018-01-30 10:36
```
mport static org.junit.Assert.assertTrue;
 
import org.junit.Rule;
import org.junit.Test;
 
import au.com.dius.pact.consumer.MessagePactBuilder;
import au.com.dius.pact.consumer.MessagePactProviderRule;
import au.com.dius.pact.consumer.Pact;
import au.com.dius.pact.consumer.PactVerification;
import au.com.dius.pact.consumer.dsl.PactDslJsonBody;
import au.com.dius.pact.model.v3.messaging.MessagePact;
import by.iba.gomel.srm.countries.MessageConverter;
import by.iba.gomel.srm.countries.messaging.validator.MessageValidator;
import io.vertx.core.json.JsonObject;
 
public class CountriesApiGatewayConsumerGetPactTest {
 
    @Rule
    public MessagePactProviderRule mockProvider = new MessagePactProviderRule(this);
    
    @Pact(provider = "api-gateway", consumer = "countries")
    public MessagePact getMessage(MessagePactBuilder builder) {
        PactDslJsonBody getBody= new PactDslJsonBody();
        getBody
            .object("metadata")
                .stringType("messageId", "test")
                .stringType("date", "test")
                .stringType("contractVersion", "test")
            .closeObject()
            .object("payload")
                .stringType("name", "srm.countries.get")
                .stringType("iri","some_iri")
            .closeObject()
            .closeObject();
        
        return builder.given("srm.countries.get_message")
                .expectsToReceive("srm.countries.get").withContent(getBody)
                .toPact();
    }
  
    @Test
    @PactVerification({ "api-gateway", "srm.countries.get_message" })
    public void testValidationForGetMessage() {    
      System.out.println(new String (mockProvider.getMessage()));
      boolean isValidMessage = MessageValidator.isValid(new MessageConverter( new JsonObject(new String (mockProvider.getMessage()))));
      assertTrue("should be validated as true", isValidMessage); 
    }
    
  
 
}
```

**Comment by uglyog** [comment] 2018-02-19 02:56
Looks like your pact file has invalid paths. There was a defect with a previous version that caused this. Are you able to re-generate the pact files with version 3.5.12?

**Comment by PDziamentsyeu** [comment] 2018-02-19 13:19
Could you give an example for 
`Looks like your pact file has invalid paths.`

**Comment by uglyog** [comment] 2018-02-22 22:45
In your pact file, values like `".metadata.date"` are invalid. That is why the verifier is rejecting it.

**Comment by PDziamentsyeu** [comment] 2018-02-26 09:51
yes, correct. In issue i described this issue. When i generate pact file in result i don't get $ symbol. In reprodused from time to time.

**Comment by uglyog** [comment] 2018-02-26 21:38
What version of the Pact libraries are you using?

**Comment by rholshausen** [comment] 2018-06-20 01:37
Looks like the cause is  not calling `.close()` after the last `.closeObject()` (see the linked issue)

**Comment by uglyog** [comment] 2018-07-01 06:00
The actual cause was the double `..closeObject()` at the end. Should be fixed now.

**Comment by uglyog** [comment] 2018-07-01 09:41
3.5.19 has been released with this fix

**Closed by uglyog** 2018-07-01 09:41 UTC
Labels: bug

**Comment by alexandre-neves-lacapitale** [comment] 2018-08-14 16:34
a
