### ISSUE TITLE
Pact verification integration with pact broker not working on version 3.5.19

### ISSUE THREAD

**Issue by LoraVolkert** [DiUS/pact-jvm#751] opened 2018-08-06 17:33 UTC
I'd noticed several tests in our pact broker show they haven't been verified for a while. I kicked off build jobs for them that include a pact verify step, and still the broker showed them as not having been verified in days.

So I looked at one of our test projects for which webhooks seemed to be working and verification and publishing all seemed pretty current. I launched a build of the consumer and everything ran as expected -- the consumer published the latest version of the test, the webhook kicked off a build job for the provider, and the provider job ran a pact verify. All three stages resulted in updated times in the pact broker.

On a hunch, I updated the version of pact in each project from 3.5.12 to 3.5.19 (the only other change from the previous build to this one was the introduction of a few kotlin dependencies to fix transitive dependency version issues). The consumer published a new test, the webhook launched a build of the provider, the provider build succeeded, but this time the pact broker did not show that the provider had verified the test since the last pact had been published.

**Comment by LoraVolkert** [comment] 2018-08-06 17:34
We are using version 2.19.1 of the broker.

**Comment by LoraVolkert** [comment] 2018-08-06 19:09
I have narrowed it down. Pact broker integration for providers works in 3.5.16, but fails in 3.5.17. So somewhere in that changeset is when things broke.

**Comment by anto-ac** [comment] 2018-08-08 16:42
Yes, I experienced the same issue with 3.5.17.

**Comment by uglyog** [comment] 2018-08-12 03:42
This is a duplicate of #738

**Closed by uglyog** 2018-08-12 03:42 UTC
Labels: duplicate

**Comment by uglyog** [comment] 2018-08-12 05:08
The main change from 3.5.16 was to change the behaviour of the `pact.verifier.publishResults` system property. This now needs to be set to `true` for the results to be published.

**Comment by LoraVolkert** [comment] 2018-08-15 15:57
Where would one set that flag?

**Comment by uglyog** [comment] 2018-08-16 08:31
It's a JVM system property. It depends on how you are running the verification. With Gradle and Maven you can use `-Dpact.verifier.publishResults=true`
