### ISSUE TITLE
AmqpTarget doesn't find @PactVerifyProvider annotation

### ISSUE THREAD

**Issue by thombergs** [DiUS/pact-jvm#763] opened 2018-08-24 09:12 UTC
I'm running a simple message provider test:

```java
@RunWith(PactRunner.class)
@Provider("userservice")
@PactFolder("../pact-message-consumer/target/pacts")
@SpringBootTest
public class MessageProviderTest {

	@TestTarget
	public final Target target = new AmqpTarget(Collections.singletonList("io.reflectoring"));

	@PactVerifyProvider("a user created message")
	public String verifyUserCreatedMessage() {
		return "{\"testParam1\": \"value1\",\"testParam2\": \"value2\"}";
	}
}
```

Executing this test results in 
```
Failures:

0) a user created message
      No annotated methods were found for interaction 'a user created message'. You need to provide a method annotated with @PactVerifyProvider("a user created message") that returns the message contents.
```

The cause for this is that the `Reflections` call in `ProviderVerifier#verifyResponseByInvokingProviderMethods` doesn't find the `@PactVerifyProvider` annotation on my test method. There must be something wrong with the setup of the `Reflections` instance (class loader?).

When I'm using the following code snippet from a test, the annotation is found:
```java
Reflections r = new Reflections(ClasspathHelper.forPackage("io.reflectoring"), new MethodAnnotationsScanner());
Set<Method> methods = r.getMethodsAnnotatedWith(PactVerifyProvider.class);
```

**Comment by uglyog** [comment] 2018-08-26 03:49
How are you running the test, from Maven or from your IDE?

**Comment by thombergs** [comment] 2018-08-26 18:40
From both Gradle and the IDE.

**Comment by thombergs** [comment] 2018-08-26 20:51
@uglyog 

I took a deeper look. In `ProviderVerifier#verifyResponseByInvokingProviderMethods()` the `ConfigurationBuilder` used for the `Reflections` instance is initialized with classpath URLs via `def urls = projectClasspath.get()`.

Running my test from the IDE, the resolved URLs are:
0 = {URL@3601} "file:/C:/Users/Tom/AppData/Local/Temp/classpath1765335879.jar"
1 = {URL@3602} "file:/C:/Users/Tom/.IntelliJIdea2018.2/system/groovyHotSwap/gragent.jar"
2 = {URL@3603} "file:/C:/Users/Tom/.IntelliJIdea2018.2/system/captureAgent/debugger-agent.jar"

None of those JARs contains my classes.

**Comment by thombergs** [comment] 2018-09-03 16:37
@uglyog did you have a chance to look into this?

**Comment by uglyog** [comment] 2018-09-08 08:26
I've run a few, and they work for me in IntelliJ. Looks like you are getting an empty classpath, not your project's. Check your run configuration in IntelliJ to see what classpath is being set.

The AmqpTarget is using `ClassLoader.getSystemClassLoader()` to get the classpath to use. You could try extending a class from AmqpTarget and use the classpath from the test class to see if that works. Just override the `setupVerifier` method and then override the `projectClasspath` field on the verifier.

**Comment by thombergs** [comment] 2018-09-10 19:52
@uglyog I still couldn't get it to work, even when overriding the `projectClasspath` field. Must be some issue with the classloader. 

I **can** get it to work when overriding the whole usage of Reflections (i.e. subclassing `AmqpTarget` and `ProviderVerifier`, but that is a very ugly workaround (see [here](https://github.com/thombergs/code-examples/tree/master/pact/pact-message-provider/src/test/java/io/reflectoring)).

Instead of using a specific classloader, I simply use `Reflections r = new Reflections(packages, new MethodAnnotationsScanner());` to scan the classpath for annotations. 

Why does `ProviderVerifier` use a specific class loader? Wouldn't it make sense to use the Reflections default as I did above?

**Comment by uglyog** [comment] 2018-09-10 22:43
The problem is that different build tools setup the classpaths in different ways. Pact-JVM also supports running verifications from Gradle, Maven, Leiningen and SBT. 

However, what we can do is default it to no classpath, and if it hasn't been overridden by one of the build plugins, then use the default.

**Comment by gumartinm** [comment] 2019-01-07 03:02
The same problem with pact-jvm-provider-junit_2.12 version 3.6.1.
AmqpTarget works from IntelliJ but it does not from maven.

**Comment by uglyog** [comment] 2019-02-16 03:59
@PMT87 @gumartinm You need to set the Maven Surefire plugin to use an isolated class loader. For example:

```xml
             <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <useSystemClassLoader>false</useSystemClassLoader>
                </configuration>
            </plugin>
```

**Comment by eranberg** [comment] 2019-03-26 20:14
@uglyog my test class setup is identical to the one @thombergs has and I am using pact-jvm-provider-junit_2.12 version 3.6.2 along with the suggested useSystemClassLoader configuration on surefire.
When building with Maven I am still getting the same error: 

`No annotated methods were found for interaction 'test message'. You need to provide a method annotated with @PactVerifyProvider("test message") that returns the message contents`

Any idea on what else I can do for this?

**Comment by uglyog** [comment] 2019-04-13 06:47
@eranberg are you able to provide your POM file?

**Comment by jon-ruckwood** [comment] 2019-04-30 09:42
@eranberg I was experiencing the same issue but with `3.6.4`. I found that after upgrading `maven-surefire-plugin`, everything started to work:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.1</version>
    <configuration>
        <useSystemClassLoader>false</useSystemClassLoader>
    </configuration>
</plugin>
```

Intermediate versions may work, however I didn't look into it.

**Comment by uglyog** [comment] 2019-05-03 06:32
Thanks @jon-ruckwood I will update the docs to specify that version as a minimum.

**Comment by eranberg** [comment] 2019-05-08 20:55
@jon-ruckwood @uglyog 
I tried:
1. upgrading the maven-surefire-plugin to 2.22.1
2. upgrading the Pact dependencies to 3.6.4
3. upgrading Maven itself to the latest 3.6.1

I still get the same error after all of these upgrades...
Any idea what to do next?

**Comment by uglyog** [comment] 2019-05-12 04:05
@eranberg have a look at https://github.com/uglyog/pact-maven-amqp-test, it is a simple project that works with Maven 3.5. You'll need to compare it to yours to work out what the issue is.

**Comment by eranberg** [comment] 2019-05-13 16:00
@uglyog Thanks for providing the github project with the testing samples. It worked out of the box for me so I am guessing some of the other parts of my technological stack is interfering with my tests.

**Comment by tylerkron** [comment] 2019-05-22 18:38
Had this issue as well.  My issue is that I am using Java 11.  Upgraded to `pact-jvm-consumer-junit` version `4.0.0-beta.2` and I have provider verification working again.

**Comment by uglyog** [comment] 2019-06-01 07:10
Closing this as there looks like there are work arounds for all the issues

**Closed by uglyog** 2019-06-01 07:10 UTC
