### ISSUE TITLE
Pact provider version 3.5.22 cannot find pacts on the broker

### ISSUE THREAD

**Issue by LoraVolkert** [DiUS/pact-jvm#771] opened 2018-09-13 17:09 UTC
I bumped my dependency from 3.5.21 to 3.5.22, which was the only change in my code. I went from successfully building 11 tests to not being able to find a single one: 

Running com.clearwateranalytics.pact.DonutsConsumerPactTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.912 s <<< FAILURE! - in com.clearwateranalytics.pact.DonutsConsumerPactTest
initializationError(com.clearwateranalytics.pact.DonutsConsumerPactTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.Exception: Did not find any pact files for provider donuts-ws

Results:

Errors: 
  DonutsConsumerPactTest.initializationError »  Did not find any pact files for ...

**Comment by mreno-EBSCO** [comment] 2018-09-14 12:56
I just ran into this and it drove me crazy because I started working on Pact with v3.5.22. After debugging the code, I believe it is a regression caused by https://github.com/DiUS/pact-jvm/pull/764

**Comment by carlzogheib** [comment] 2018-09-22 23:49
That's odd, i thought the change should allow `pactbroker.consumers` to be empty so that it tests all consumers. @uglyog isn't that right?

**Comment by uglyog** [comment] 2018-09-23 01:01
I'll have a look, it may be an unintentional regression. It should have not had an effect if not used.

**Comment by uglyog** [comment] 2018-09-23 07:05
3.5.23 has been released with this fix

**Closed by uglyog** 2018-09-23 07:05 UTC
Labels: bug
