### ISSUE TITLE
@PactVerifications does only use first fragment

### ISSUE THREAD

**Issue by cladob** [DiUS/pact-jvm#820] opened 2018-11-30 12:47 UTC
Using @PactVerification with many fragments will only use the first one. Example

@PactVerifications( {
       @PactVerification(fragment = "fragment1", value= "provider1")
       @PactVerification(fragment = "fragment2", value= "provider2")
})
@Test
public void testMethod() {
......

will only verify the testMethod against the fragment1 (provider1), while fragment2 (provider2) will be ignored, so the test will fail.

I used au.com.dius:pact-jvm-consumer-java8_2.12:3.5.23 and  au.com.dius:pact-jvm-consumer-junit_2.12:3.5.23

Is it possible somehow to combine many fragments, different providers, for test verification ?

**Comment by uglyog** [comment] 2019-02-03 01:16
I am not able to reproduce this. Have a look at this test https://github.com/DiUS/pact-jvm/blob/v3.5.x/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderWithMultipleFragmentsTest.java#L103 and compare it to yours.

**Comment by cladob** [comment] 2019-03-12 22:15
I tested your TestClass and it works! I adapted it for the version 2.4.20 and it also works. Sorry for the false finding.

**Comment by cladob** [comment] 2019-04-23 20:16
The Issue actually happens when there is more than one Fragment from the same Provider:

@PactVerifications( {
@PactVerification(fragment = "**fragment11**", value= "**provider1**"),
@PactVerification(fragment = "**fragment12**", value= "**provider1**"),
@PactVerification(fragment = "fragment2", value= "provider2")
})
@test
public void testMethod() {
......
 <code that indirectly uses fragment11, fragment12 and fragment2>
......
}

The testMethod() will fail because fragment12 seems not to be loaded within provider1's MockServer instance. The frament2 gets properly loaded.

**Comment by uglyog** [comment] 2019-05-03 06:12
It doesn't make sense to have multiple pacts for the same provider in the same test. It should be an error instead.

The other option would be to just merge the pacts into a single one. That would be effectively the same as having just fragment1 with all the interactions.

**Comment by cladob** [comment] 2019-05-11 18:59
the name "fragment" for the PactVerification implies a part of the interactions with the provider. What I use to do is to use many fragments for on provider that I can later combine in many different tests. Some tests use only one fragment while other tests use two or more fragments all from same Provider

I looked at how PactVerifications is currently used and for one Provider if there are more fragments it takes only the first one. Wouldn't be possible to consider for one Provider all listed fragments  ? I see the possibility to merge all fragments' interactions.

**Comment by uglyog** [comment] 2019-05-12 06:38
3.6.7 is released with support for this.

**Closed by uglyog** 2019-05-12 06:38 UTC
