### ISSUE TITLE
@PactBroker not reading Spring properties with JUnit 5

### ISSUE THREAD

**Issue by arhohuttunen** [DiUS/pact-jvm#1023] opened 2020-02-21 06:44 UTC
If you provide system properties in Spring `application.yml` these won't be read by the `@PactBroker` annotation when running with JUnit 5. This works fine if you provide them as normal system properties.

This issue seems to have been fixed for the JUnit 4 runners in here: https://github.com/DiUS/pact-jvm/issues/632

I can see that the problem has been fixed by adding a property resolver, and that it is also possible to pass a `valueResolver` attribute for the `@PactBroker` annotation. However, since you need a Spring context to be able to create such a resolver for Spring, it cannot be done with the annotation.

I also tried to add a resolver into `PactVerificationContext` in `@BeforeEach` but that didn't seem to do the trick.

**Comment by vtapadia** [comment] 2020-02-21 10:39
I am also having the same issue.
The preferred approach to ask questions on stackflow did not help either.
https://stackoverflow.com/questions/60153108/provider-test-integration-with-pact-broker-for-spring-boot-junit5-configuratio

Waiting for the answer

**Comment by uglyog** [comment] 2020-02-22 06:53
I've created a new module pact-jvm-provider-junit5-spring with a TestTemplateInvocationContextProvider that extends the current JUnit 5 one (PactVerificationSpringProvider). This should allow you to configure all the properties in the Spring context.

**Comment by arhohuttunen** [comment] 2020-02-22 07:30
That’s awesome! Thank you for such a quick response to the issue. This will make the developer experience smoother when running tests out of the box, with the broker having a default configuration in the properties file.

**Comment by vtapadia** [comment] 2020-02-28 12:03
HI @uglyog , I noticed a small inconsistency in the implementation of the [SpringEnvironmentResolver.kt ](https://github.com/DiUS/pact-jvm/blob/master/provider/pact-jvm-provider-junit5-spring/src/main/kotlin/au/com/dius/pact/provider/spring/junit5/SpringEnvironmentResolver.kt)

The `propertyDefined()` method relies only on environment, while the `resolveValue() ` uses SystemPropertyResolver also as backup. 
Also, the Spring _environment_ property resolution considers the system properties also when resolving a value. That has a higher preference. Any specific reason why?

**Comment by uglyog** [comment] 2020-03-07 03:50
@vtapadia I've removed the SystemPropertyResolver fallback

**Comment by uglyog** [comment] 2020-03-07 05:14
@vtapadia removing the fallback breaks the pact loader, so I'm reverting the change

**Comment by arhohuttunen** [comment] 2020-03-13 09:38
Tested this with version 4.0.7 and replaced the `PactVerificationInvocationContextProvider` with the `PactVerificationSpringProvider`. Also added the missing properties to `application.yml`.

However, I'm still getting this:

```
java.lang.IllegalArgumentException: Invalid pact broker host specified ('${pactbroker.host:}'). Please provide a valid host or specify the system property 'pactbroker.host'.

	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.getPactBrokerSource(PactBrokerLoader.kt:176)
	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.description(PactBrokerLoader.kt:62)
	at au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider.resolvePactSources(PactJUnit5VerificationProvider.kt:395)
	at au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider.provideTestTemplateInvocationContexts(PactJUnit5VerificationProvider.kt:366)
```

The stack trace suggests that it's still using the `PactVerificationInvocationContextProvider` and not the Spring specific one.

Am I missing something here?

**Comment by arhohuttunen** [comment] 2020-03-14 15:18
I did some debugging with this, and it seems that while the original commit to implement this worked, this line on the following commit has broken the functionality:

https://github.com/DiUS/pact-jvm/commit/2f1070bc72bf3b70372a77191c3525c6327aae47#diff-d732216607e72eef90df38a4cabc68efR395

It seems that calling `it.description()` tries to already use a resolver, but it has not yet been correctly set.

**Closed** 2020-03-21 16:31 UTC
Labels: enhancement

**Comment by uglyog** [comment] 2020-03-22 23:21
4.0.8 released with this change

**Comment by gustavotpd** [comment] 2020-07-29 18:41
I'm using this dependency

        
        <dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-provider-junit5</artifactId>
            <version>4.0.10</version>
        </dependency>

My code:

@PactBroker(scheme = "https", host = "${pactbroker.host}", authentication = @PactBrokerAuth(token = "${pactbroker.auth.token}"))
@Provider("PriceService")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@ExtendWith(SpringExtension.class)

public class PriceServicePactTests {

	@LocalServerPort
	private final int port = 8082;
	ObjectMapper objectMapper = new ObjectMapper();
	@MockBean
	private PriceDAO priceDao;

	@BeforeEach
	public void setupTest(final PactVerificationContext context) {
		System.setProperty("pact.provider.tag", "dev");
		System.setProperty("pact.provider.version", "1.0.0");
                context.setTarget(new HttpTestTarget("localhost", port, "/"));
  	}

	@BeforeClass
	public void enablePublishingPact() {
	   	System.setProperty("pact.verifier.publishResults", "true");
	}

	@TestTemplate
	@ExtendWith(PactVerificationInvocationContextProvider.class)
	void pactVerificationTestTemplate(final PactVerificationContext context) {
		context.verifyInteraction();
	}

and facing the same problem: **java.lang.RuntimeException: Could not resolve property "pactbroker.host" in the system properties or environment variables and no default value is supplied**

any help would be appreciated.

Thanks in advance.

**Comment by uglyog** [comment] 2020-08-08 02:44
@gustavotpd `pactbroker.host` needs to be defined as a JVM system property somewhere. See https://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html on how to do this with the Maven Surfire plugin, which is what runs the tests with Maven.

**Comment by vijays2017** [comment] 2020-08-26 13:37
Hi, I want to disable pact tests in local build . With regards to same I am using `@IgnoreNoPactsToVerify (ignoreIoErrors = "${pact.verification.ignoreIoErrors}")` and I am setting the property in system arg as `mvn -s H:\settings.xml -DargLine="-Dpact.verification.ignoreIoErrors=true` however I still get the error - 

 Could not resolve property "${pact.verification.ignoreIoErrors}" in the system properties or environment variables and no default 
value is supplied

I am using pact plugin
 <plugin>
        <groupId>au.com.dius</groupId>
        <artifactId>pact-jvm-provider-maven_2.12</artifactId>
        <version>${pact.jvmprovider}</version>

Can you pls help?

**Comment by uglyog** [comment] 2020-09-05 03:45
@vijays2017 the property needs to be set on the test JVM. See https://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html on how to do this with the Maven Surfire plugin, which is what runs the tests with Maven.

**Comment by bijancn** [comment] 2021-09-15 14:46
@uglyog `@ExtendWith(PactVerificationSpringProvider::class)` should really be mentioned in the docs. And also that you can only set `usePreemptiveAuthentication` via system properties. No matter what loader you hook up.

I ended up with this code to make it work
```
    @BeforeAll
    fun beforeAll() {
        System.setProperty("pact.pactbroker.httpclient.usePreemptiveAuthentication", "true")
    }
```

**Comment by uglyog** [comment] 2021-09-18 23:48
@bijancn Can you expand on what you mean by "should really be mentioned in the docs". It is documented here: https://github.com/pact-foundation/pact-jvm/tree/master/provider/junit5spring#usage

**Comment by bijancn** [comment] 2021-09-20 08:37
Sure, sorry. In the documentation, it says
```
@ExtendWith(SpringExtension.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@Provider("Animal Profile Service")
@PactBroker
public class ContractVerificationTest {
  
    @TestTemplate
    @ExtendWith(PactVerificationSpringProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
      context.verifyInteraction();
    }
    
}
```

So, the `PactVerificationSpringProvider` is used on the method but not on the class. This does not allow me to load e.g. `pactbroker.host` from the `application.yaml`. Instead, I need to do something like this
```
@ExtendWith(PactVerificationSpringProvider::class) // this allows loading from Spring Context and thus resources/application.yaml and env variables
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@Provider("Animal Profile Service")
@PactBroker()
public class ContractVerificationTest {
```

**Comment by uglyog** [comment] 2021-09-27 02:01
@bijancn I just verified with my test project: https://github.com/uglyog/springboot-junit5-test

That project works loading the broker properties from `application.yaml` with the annotation on the method. It should make no difference if it is on the method or on the class.

**Comment by bijancn** [comment] 2021-09-27 05:55
Could it be a Java vs Kotlin thing? It definitely doesn't work for me. But maybe you can also link to your example project? I wasn't aware of that and it would have helped me.

**Comment by jmb-missionlane** [comment] 2021-10-12 16:55
Agreed with @bijancn this issue should be re-opened as I have been fighting to figure out why my test kept failing (in Kotlin) because it couldn't load my properties.

`Could not resolve property "pactbroker.hostname" in the system properties or environment variables and no default value is supplied
java.lang.RuntimeException: Could not resolve property "pactbroker.hostname" in the system properties or environment variables and no default value is supplied
	at au.com.dius.pact.core.support.expressions.SystemPropertyResolver.resolveValue(SystemPropertyResolver.kt:20)
`
With my test (you can see the first two annotations is me fighting to figure out why the properties in my @PactBroker aren't being brought in):

`@ActiveProfiles("test")
@TestPropertySource("classpath:application-test.yml")
@Provider("test-Provider")
@PactBroker(
    host = "\${pactbroker.hostname}", scheme = "https",
    authentication = PactBrokerAuth(username = "\${pactbroker.username}", password = "\${pactbroker.password}")
)
@SpringBootTest(classes = [Application::class], webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT, properties = ["server.port=8091"])
class PactTest {

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider::class)
    fun pactVerificationTestTemplate(context: PactVerificationContext, request: HttpRequest) {
        request.addHeader("Content-Type", "application/json")
        // must come after request modification
        context.verifyInteraction()
    }

    @BeforeEach
    fun before(context: PactVerificationContext) {
        context.target = HttpTestTarget("localhost", 8091, "/")
    }

    @State("there is a client token")
    fun clientToken()  }

**Comment by ViSilver** [comment] 2023-05-03 08:50
The issue is that the `application-test.yaml` is not considered unless `@ActiveProfiles("test")` is specified. I think this is counterintuitive and the main reason for confusion.

**Comment by rholshausen** [comment] 2023-05-08 00:37
That is standard Spring behavior. Pact-JVM is not Spring specific.
